angular.module("beer-rate.home").service("beerService", function(){
    
    return {
        getBeers: getBeers
    }

    function getBeers(){
        return [
            { id: 1, imgSmall: "/app/img/150/beer-1.jpg", img: "/app/img/300/beer-1.jpg", name: "Tyskie", brewery: "piwowarnia 1", rate: 2, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum at mi a tincidunt. Nulla a pretium ante. Aliquam finibus, mi et eleifend eleifend, massa elit pellentesque nisl, ac elementum turpis augue quis massa. In molestie metus nibh, eget ultricies mi accumsan eget. Nullam a quam mattis metus sagittis viverra. Phasellus nec dignissim erat, eu tempus lorem. Fusce arcu odio, ultricies ut erat sed, laoreet faucibus nisi. Proin mollis aliquet mi at aliquam. Maecenas volutpat orci vel magna molestie, eget ullamcorper metus bibendum. Quisque posuere purus ac neque feugiat tristique. Nunc id fermentum diam."},
            { id: 2, imgSmall: "/app/img/150/beer-2.jpg", img: "/app/img/300/beer-2.jpg", name: "Zuber", brewery: "piwowarnia 1", rate: 3 , description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum at mi a tincidunt. Nulla a pretium ante. Aliquam finibus, mi et eleifend eleifend, massa elit pellentesque nisl, ac elementum turpis augue quis massa. In molestie metus nibh, eget ultricies mi accumsan eget. Nullam a quam mattis metus sagittis viverra. Phasellus nec dignissim erat, eu tempus lorem. Fusce arcu odio, ultricies ut erat sed, laoreet faucibus nisi. Proin mollis aliquet mi at aliquam. Maecenas volutpat orci vel magna molestie, eget ullamcorper metus bibendum. Quisque posuere purus ac neque feugiat tristique. Nunc id fermentum diam."},
            { id: 3, imgSmall: "/app/img/150/beer-3.jpg", img: "/app/img/300/beer-3.jpg", name: "Volt", brewery: "piwowarnia 1", rate: 5, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum at mi a tincidunt. Nulla a pretium ante. Aliquam finibus, mi et eleifend eleifend, massa elit pellentesque nisl, ac elementum turpis augue quis massa. In molestie metus nibh, eget ultricies mi accumsan eget. Nullam a quam mattis metus sagittis viverra. Phasellus nec dignissim erat, eu tempus lorem. Fusce arcu odio, ultricies ut erat sed, laoreet faucibus nisi. Proin mollis aliquet mi at aliquam. Maecenas volutpat orci vel magna molestie, eget ullamcorper metus bibendum. Quisque posuere purus ac neque feugiat tristique. Nunc id fermentum diam."},
            { id: 4, imgSmall: "/app/img/150/beer-4.jpg", img: "/app/img/300/beer-4.jpg", name: "Lech", brewery: "rudy browar", rate: 7, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum at mi a tincidunt. Nulla a pretium ante. Aliquam finibus, mi et eleifend eleifend, massa elit pellentesque nisl, ac elementum turpis augue quis massa. In molestie metus nibh, eget ultricies mi accumsan eget. Nullam a quam mattis metus sagittis viverra. Phasellus nec dignissim erat, eu tempus lorem. Fusce arcu odio, ultricies ut erat sed, laoreet faucibus nisi. Proin mollis aliquet mi at aliquam. Maecenas volutpat orci vel magna molestie, eget ullamcorper metus bibendum. Quisque posuere purus ac neque feugiat tristique. Nunc id fermentum diam."},
            { id: 5, imgSmall: "/app/img/150/beer-5.jpg", img: "/app/img/300/beer-5.jpg", name: "Kasztelan", brewery: "rozklapiocha brew co", rate: 6, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum at mi a tincidunt. Nulla a pretium ante. Aliquam finibus, mi et eleifend eleifend, massa elit pellentesque nisl, ac elementum turpis augue quis massa. In molestie metus nibh, eget ultricies mi accumsan eget. Nullam a quam mattis metus sagittis viverra. Phasellus nec dignissim erat, eu tempus lorem. Fusce arcu odio, ultricies ut erat sed, laoreet faucibus nisi. Proin mollis aliquet mi at aliquam. Maecenas volutpat orci vel magna molestie, eget ullamcorper metus bibendum. Quisque posuere purus ac neque feugiat tristique. Nunc id fermentum diam."},
            { id: 6, imgSmall: "/app/img/150/beer-6.jpg", img: "/app/img/300/beer-6.jpg", name: "Tatra", brewery: "tys browar", rate: 1, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum at mi a tincidunt. Nulla a pretium ante. Aliquam finibus, mi et eleifend eleifend, massa elit pellentesque nisl, ac elementum turpis augue quis massa. In molestie metus nibh, eget ultricies mi accumsan eget. Nullam a quam mattis metus sagittis viverra. Phasellus nec dignissim erat, eu tempus lorem. Fusce arcu odio, ultricies ut erat sed, laoreet faucibus nisi. Proin mollis aliquet mi at aliquam. Maecenas volutpat orci vel magna molestie, eget ullamcorper metus bibendum. Quisque posuere purus ac neque feugiat tristique. Nunc id fermentum diam."},
            { id: 7, imgSmall: "/app/img/150/beer-1.jpg", img: "/app/img/300/beer-1.jpg", name: "Harnas", brewery: "tys browar", rate: 8, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum at mi a tincidunt. Nulla a pretium ante. Aliquam finibus, mi et eleifend eleifend, massa elit pellentesque nisl, ac elementum turpis augue quis massa. In molestie metus nibh, eget ultricies mi accumsan eget. Nullam a quam mattis metus sagittis viverra. Phasellus nec dignissim erat, eu tempus lorem. Fusce arcu odio, ultricies ut erat sed, laoreet faucibus nisi. Proin mollis aliquet mi at aliquam. Maecenas volutpat orci vel magna molestie, eget ullamcorper metus bibendum. Quisque posuere purus ac neque feugiat tristique. Nunc id fermentum diam."}
        ];
    }
});